# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Compile SDK
android.suppressUnsupportedCompileSdk=34

# Gradle / Kotlin
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin
kotlin.code.style=official

# Build performance
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
